### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by megawac** [ganemone/NodeRequirer#40]
Haven't looked into it to far but cloning the latest master fails with an import error on Ubuntu 14.04

```sh
reloading plugin NodeRequirer.NodeRequirer
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1529, in _find_and_load_unlocked
ImportError: No module named 'NodeRequirer.NodeRequirer'
```

The last working revision was https://github.com/ganemone/NodeRequirer/commit/6866cedd9c132c12565a02227c511932b7c2a0bb

**Comment by megawac** [comment]
Looks like this may be specific to build 3065, works on 3074
