### ISSUE TITLE
FuzzyWuzzy import problem

### ISSUE THREAD

**Issue by ncthis** [ganemone/NodeRequirer#62]
```bash
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/nadeesha/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 11, in <module>
    from NodeRequirer.src.dependencies.fuzzywuzzy.fuzzywuzzy import process
ImportError: No module named 'NodeRequirer.src.dependencies.fuzzywuzzy.fuzzywuzzy'
```

I think the submodule (if that was your intention) was not linked properly. I was able to get it working after restoring to `0.4.1`.

**Comment by chuyik** [comment]
For anyone wants a quick fix, please do following steps:
1. add a `.gitmodule` file to `~/Library/Application Support/Sublime Text 3/Packages/NodeRequirer` with the following content:

```
[submodule "fuzzywuzzy"]
    path = src/dependencies/fuzzywuzzy
    url = git://github.com/seatgeek/fuzzywuzzy.git
```

2. run `git submodule update --init --recursive` to download the submodule.

3. If not working, try to edit `fuzzywuzzy/fuzzywuzzy/utils.py` line 3:
```
from .string_processing import StringProcessor
```

4. Restart ST3, done!

**Comment by ganemone** [comment]
Should be fixed as of `0.4.4`

**Comment by chenglou** [comment]
On 0.4.7. Gives:

```
    module = utils.best_fuzzy_match(files, word_text)
AttributeError: 'module' object has no attribute 'best_fuzzy_match'
```

**Comment by ganemone** [comment]
@chenglou Sublime Text sucks with cache invalidation. Basically it doesn't look at changes of any files other than the main file until you restart the application. Quitting and restarting sublime should fix your issue.

**Comment by dantman** [comment]
You can also install [Package Reloader](https://packagecontrol.io/packages/Package%20Reloader) which will use the `.build` file to reload files other than the main file.
