### ISSUE TITLE
AttributeError: 'module' object has no attribute 'splitext'

### ISSUE THREAD

**Issue by kamilkp** [ganemone/NodeRequirer#99]
When I select a file from the popup menu I get:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/kamil/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 234, in run
    module_info = get_module_info(args['module'], self.view)
  File "/Users/kamil/Library/Application Support/Sublime Text 3/Packages/NodeRequirer/NodeRequirer.py", line 341, in get_module_info
    module_name, extension = utils.splitext(module_name)
AttributeError: 'module' object has no attribute 'splitext'
```

**Comment by megawac** [comment]
are you using the latest version? did you use a git clone of the repo or package control installation?

I fixed this bug recently so curious #94
